packages:
  - "apps/*"
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/engines': true
  '@swc/core': set this to true or false
  argon2: true
  esbuild: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nestjs/common@12.1.2'
  - '@nestjs/core@12.1.2'
  - '@nestjs/platform-express@12.1.2'
