packages:
  - "apps/*"
allowBuilds:
  '@prisma/engines': true
  argon2: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nestjs/common@12.1.2'
  - '@nestjs/core@12.1.2'
  - '@nestjs/platform-express@12.1.2'
