const HY: Record<string, string> = {
  AM: "Հայաստան",
  RU: "Ռուսաստան",
  KZ: "Ղազախստան",
  GE: "Վրաստան",
  AZ: "Ադրբեջան",
  UA: "Ուկրաինա",
  BY: "Բելառուս",
  MD: "Մոլդովա",
  UZ: "Ուզբեկստան",
  TR: "Թուրքիա",
  IR: "Իրան",
  IQ: "Իրաք",
  SY: "Սիրիա",
  LB: "Լիբանան",
  JO: "Հորդանան",
  IL: "Իսրայել",
  SA: "Սաուդյան Արաբիա",
  AE: "Արաբական Միացյալ Էմիրություններ",
  QA: "Կատար",
  KW: "Քուվեյթ",
  EG: "Եգիպտոս",
  US: "ԱՄՆ",
  CA: "Կանադա",
  GB: "Միացյալ Թագավորություն",
  DE: "Գերմանիա",
  FR: "Ֆրանսիա",
  IT: "Իտալիա",
  ES: "Իսպանիա",
  PT: "Պորտուգալիա",
  NL: "Նիդեռլանդներ",
  BE: "Բելգիա",
  CH: "Շվեյցարիա",
  AT: "Ավստրիա",
  PL: "Լեհաստան",
  CZ: "Չեխիա",
  RO: "Ռումինիա",
  BG: "Բուլղարիա",
  GR: "Հունաստան",
  SE: "Շվեդիա",
  NO: "Նորվեգիա",
  FI: "Ֆինլանդիա",
  EE: "Էստոնիա",
  LV: "Լատվիա",
  LT: "Լիտվա",
  IN: "Հնդկաստան",
  CN: "Չինաստան",
};

const EN: Record<string, string> = {
  AM: "Armenia",
  RU: "Russia",
  KZ: "Kazakhstan",
  GE: "Georgia",
  AZ: "Azerbaijan",
  UA: "Ukraine",
  BY: "Belarus",
  MD: "Moldova",
  UZ: "Uzbekistan",
  TR: "Turkey",
  IR: "Iran",
  IQ: "Iraq",
  SY: "Syria",
  LB: "Lebanon",
  JO: "Jordan",
  IL: "Israel",
  SA: "Saudi Arabia",
  AE: "United Arab Emirates",
  QA: "Qatar",
  KW: "Kuwait",
  EG: "Egypt",
  US: "United States",
  CA: "Canada",
  GB: "United Kingdom",
  DE: "Germany",
  FR: "France",
  IT: "Italy",
  ES: "Spain",
  PT: "Portugal",
  NL: "Netherlands",
  BE: "Belgium",
  CH: "Switzerland",
  AT: "Austria",
  PL: "Poland",
  CZ: "Czechia",
  RO: "Romania",
  BG: "Bulgaria",
  GR: "Greece",
  SE: "Sweden",
  NO: "Norway",
  FI: "Finland",
  EE: "Estonia",
  LV: "Latvia",
  LT: "Lithuania",
  IN: "India",
  CN: "China",
};

const RU: Record<string, string> = {
  AM: "Армения",
  RU: "Россия",
  KZ: "Казахстан",
  GE: "Грузия",
  AZ: "Азербайджан",
  UA: "Украина",
  BY: "Беларусь",
  MD: "Молдова",
  UZ: "Узбекистан",
  TR: "Турция",
  IR: "Иран",
  IQ: "Ирак",
  SY: "Сирия",
  LB: "Ливан",
  JO: "Иордания",
  IL: "Израиль",
  SA: "Саудовская Аравия",
  AE: "ОАЭ",
  QA: "Катар",
  KW: "Кувейт",
  EG: "Египет",
  US: "США",
  CA: "Канада",
  GB: "Великобритания",
  DE: "Германия",
  FR: "Франция",
  IT: "Италия",
  ES: "Испания",
  PT: "Португалия",
  NL: "Нидерланды",
  BE: "Бельгия",
  CH: "Швейцария",
  AT: "Австрия",
  PL: "Польша",
  CZ: "Чехия",
  RO: "Румыния",
  BG: "Болгария",
  GR: "Греция",
  SE: "Швеция",
  NO: "Норвегия",
  FI: "Финляндия",
  EE: "Эстония",
  LV: "Латвия",
  LT: "Литва",
  IN: "Индия",
  CN: "Китай",
};

/** Same labels on the server and in the browser. `hy` has no reliable Intl region data. */
export function countryName(iso: string, locale: string): string {
  const table = locale.startsWith("ru") ? RU : locale.startsWith("en") ? EN : HY;
  return table[iso] ?? iso;
}
